### ISSUE TITLE
bug in the .bad file not reinitiated when new file open

### ISSUE THREAD

**Issue by sophiechen** [anywave/anywave#17]
Lorsque Anywave reste ouvert et qu'on ouvre un autre fichier de donnée, le fichier .bad n'est pas réinitialisé. Il garde en mémoire les labels des capteurs marqués comme bad du fichier précédemment. 
Je me sers de ce fichier pour prendre en compte les capteurs bad dans Fieldtrip

**Comment by maedoc** [comment]
The montage manager [generates teh bads file](https://github.com/anywave/anywave/blob/master/src/AnyWave/Montage/AwMontageManager.cpp#L283) based on its private bad channels list `m_badChannelLabels`. 

When opening a file, the manager [intializes](https://github.com/anywave/anywave/blob/master/src/AnyWave/Montage/AwMontageManager.cpp#L260) will load a bads file if it exists, but otherwise, `m_badChannelLabels` remains untouched.

When AnyWave [opens a file](https://github.com/anywave/anywave/blob/master/src/AnyWave/AnyWave.cpp#L617), it seems that it grabs the existing instances of all objects instead of creating new ones, which probably explains this bug: the montage manager is not recreated for the new file, and the list of bad channels is not reinitialized, so the bads list contains bads from the previous file(s).

**Comment by maedoc** [comment]
Pull request #18 fixes this bug, will let @bcolombet merge the commit.

**Comment by bcolombet** [comment]
Yes You are right. Managers objects are instantiated at startup and demain active until AnyWave is closed.
Have a look at cleanUp method which is présent in all these objects to solve that bug.
