### ISSUE TITLE
Artifacts in exported files

### ISSUE THREAD

**Issue by Roehrin** [anywave/anywave#9]
After exporting a file using Brain Analyser Writer, some channels exhibit jumps in voltage. An example is illustrated below:

![issue_anywave](https://cloud.githubusercontent.com/assets/10562612/6821789/da7ea7d4-d2da-11e4-9af2-c16b323819d6.PNG)

**Comment by bcolombet** [comment]
Thanks for reporting.

**Comment by bcolombet** [comment]
This is a side effect of filters due to the fact that AnyWave exports chunks of data (30s length).

This issue has been fixed and the the next release (April 2015) will no more generate artifacts.

Note hat AnyWave will filter the entire data before saving it to disk, meaning that a large amount of memory may be required. 

We definitively suggest using the 64 bit versions of AnyWave.

**Comment by maedoc** [comment]
Was this an effect of filtering? If so, the data could be exported in chunks, but keep the filter's state when doing the next chunk so that the result is continuous. 

We could prototype/test in MATLAB first.
